// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/autflow-ux/DashboardPolish.tsx": () => import("../components/mockups/autflow-ux/DashboardPolish.tsx"),
  "./components/mockups/autflow-ux/EmptyState.tsx": () => import("../components/mockups/autflow-ux/EmptyState.tsx"),
  "./components/mockups/autflow-ux/ErrorHandling.tsx": () => import("../components/mockups/autflow-ux/ErrorHandling.tsx"),
  "./components/mockups/autflow-ux/LoadingSkeleton.tsx": () => import("../components/mockups/autflow-ux/LoadingSkeleton.tsx"),
  "./components/mockups/autflow-ux/Onboarding.tsx": () => import("../components/mockups/autflow-ux/Onboarding.tsx")
};
